[package]
name = "javascript-canister"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["canister"]

[workspace.dependencies]
candid = "0.10.8"
rquickjs = "0.6.2"

[dependencies]
candid = { workspace = true }
rquickjs = { workspace = true }

[dev-dependencies]
pocket-ic = "3.1.0"
